### ISSUE TITLE
Incompatible with serverless-http

### ISSUE THREAD

**Issue by esetnik** [arabold/serverless-sentry-plugin#22]
This plugin appears to be incompatible with [serverless-http](https://github.com/dougmoscrop/serverless-http).

Example:
```js
module.exports.api = RavenLambdaWrapper.handler(Raven, serverless(app));
```

it works fine when running the code locally using [serverless-offline](https://github.com/dherault/serverless-offline)

but when running on lambda I get `Task timed out after 6.01 seconds` in the cloudwatch logs and a response that looks like.

```
{
    "message": "Internal server error"
}
```

**Comment by arabold** [comment]
I'm sorry to hear that. Unfortunately I'm not familiar with `serverless-http` so I'm not of much help here. This could be an issue with `context.callbackWaitsForEmptyEventLoop` that will be fixed in an upcoming release soon. If you have additional details or a simple sample project that demonstrates the issue, that would be helpful.

**Comment by ineffyble** [comment]
FYI, I just tried to integrate serverless-sentry with serverless-http in the same method described, and it hasn't encountered this error.
