### ISSUE TITLE
Issue : For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

### ISSUE THREAD

**Issue by igoralvesSsense** [arabold/serverless-sentry-plugin#25]
Following the instructions this is what I have:

```
serverless.yml
custom:
  variables: ${file(config/serverless/${self:provider.stage}.yml)}
  sentry:
      dsn: "https://xxxxxxx@sentry.io/xxxxxxxx"

plugins:
  - serverless-delete-loggroups
  - serverless-plugin-typescript
  - serverless-plugin-existing-s3
  - serverless-sentry
#  - serverless-sentry-lib

```

And this is how I am using the code to send the message to Sentry:
```
...
import * as Raven from 'raven';
Raven.config('https://xxxxxxx@sentry.io/xxxxxxxx').install();
Raven.captureException('test 7');

```

This is the error I am getting when run dev in local and in AWS:
```
sls invoke local --function functionName --stage dev --path tests/events/test.json --profile testprof

Error --------------------------------------------------
 
  data-pipeline-qa Unable to validate the following destination configurations
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

After I set the variable SLS_DEBUG to "*" like this:
```
  environment:
      SLS_DEBUG: "*"
```
I am still getting the same error.

But if I change the serverless.yml to:
```
plugins:
  - serverless-delete-loggroups
  - serverless-plugin-typescript
  - serverless-plugin-existing-s3
#  - serverless-sentry
  - serverless-sentry-lib
#  - serverless-plugin-optimize
```
It runs ok. I can see the message in Sentry.

But if I try do deploy for test inside AWS I get the error:

```
Error --------------------------------------------------
 
  data-pipeline-qa Unable to validate the following destination configurations
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable. 
```
AND if I set the value for SLS_DEBUG as required in the error to 
```
  environment:
    SLS_DEBUG: "*"
```
It runs ok locally - I mean I can see the message inside Sentry,

But if I try to deploy in AWS i get the previous error again:
```
Error --------------------------------------------------
 
  data-pipeline-qa Unable to validate the following destination configurations
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

```

**Comment by arabold** [comment]
Hi @igoralvesSsense ,

I think these are two unrelated issues. 

First of all, only `serverless-sentry` can be used as a Serverless plugin in the `plugins` section of `serverless.yaml`. If you add `serverless-sentry-lib` it just wont do anything, that's why your second test with `serverless-sentry` commented out "works". In that case the plugin isn't used.

If you _do_ use the `serverless-sentry` plugin you don't have to explicitly initialize it with `Raven.config(...)` anymore. It will be initialized automatically using the configuration options passed in the `serverless.yaml`.


The error `data-pipeline-qa Unable to validate the following destination configurations` is most likely unrelated to `serverless-sentry` or `serverless-sentry-lib`. It's probably a misconfiguration of S3 or SNS, or maybe some incompatibility between another plugin such as `serverless-plugin-existing-s3`. Here's a knowledge base article for AWS I found in this context: https://aws.amazon.com/premiumsupport/knowledge-center/unable-validate-destination-s3/

If you don't mind posting your full `serverless.yaml` and some additional details here, I or somebody else might be able to help.

**Comment by dm-grinko** [comment]
**Check serverless.yml code formatting!**
https://stackoverflow.com/a/56961524/6108211
